- README.md
- beams/sequencer/SequenceClient.py
- beams/sequencer/SequenceServer.py
- beams/sequencer/Sequencer.py
- beams/sequencer/helpers/PriorityQueue.py
- beams/sequencer/helpers/Worker.py
- beams/sequencer/remote_calls/sequencer.proto
- tests/TestPriorityQueue.py
- tests/TestWorker.py
Still building out bones for this thing. Goal of this PR is to allow for requests to be plumbed all the way to generated trees. This gets us all the way up to but not including tree generation.
Added test coverage for the `Worker` object as well as new `PriorityQueue` object.
Updated `Sequencer` main object to launch threads required for runtime specifically:
* message handler thread: parses requests into the tree structure that will actually be ticked
* sequence server thread: GRPC process that accepts reqests
* main thread: thing that will tick jobs
I added a PriorityQueue object to `helpers` as this is the standard way to ensure you sequencer chooses the correct task to begin execution on . In the future we will need to make sure that when it receives a higher priority task than the …
> Joshc slac/message handling

- Makefile
- README.md
- beams/sequencer/SequenceServer.py
- beams/sequencer/Sequencer.py
- beams/sequencer/helpers/PriorityQueue.py
- beams/sequencer/helpers/README.md
- beams/sequencer/helpers/Worker.py
- beams/sequencer/remote_calls/sequencer.proto
This PR serves to deliver the server object that coordinates handling remote procedure call commands, interpreting the commands **to** be generated into trees and providing the thread (or in python parlance, the process)
This PR may serve as valuable to look at for convenient mechanisms to keep object aligned between processes. As done with PriorityQueue here. This can be be wrapped in more general abstraction
> last of infrastructure needed to handle commands prior to tree generation

- beams/behavior_tree/CheckAndDo.py
- beams/tests/test_check_and_do.py
- beams/tests/test_tree_generator.py
- beams/tree_generator/TreeSerializer.py
- docs/source/upcoming_release_notes/20-rebase_the_CheckAndDo_class_such_that_it_extends_base_class_py_trees.composites.Selector_this_can_be_seen_as_the_first_of_beams.idioms.rst
As suggested in https://github.com/pcdshub/BEAMS/issues/20 we should rebase the `CheckAndDo` class such that it extends base class `py_trees.composites.Selector` this can be seen as the first of `beams.idioms`
**Critical Note**: It is now on the 'user' to call `setup_with_descendants()` before ticking these nodes
This will make it much easier to chain together trees (nested, recursive trees).
**Note**:
This does not address the really unfortunate de-serialization architecture of  this being the  definition of the in memory class (called TreeSpec): https://github.com/pcdshub/BEAMS/blob/717525d747594a9a1675304edd298f6044441122/beams/tree_generator/TreeSerializer.py#L129-L143 that holds a "nested" or multi `CheckAndDo` that itself is currently retrieved with …
> REF: make CheckAndDo of base class py_trees.composites.Selector

- beams/tests/test_check_and_do.py
- beams/tests/test_tree_generator.py
- beams/tests/test_worker.py
- docs/source/upcoming_release_notes/29-fix-test-worker.rst
Closes #27 
There was a fun bug in our Worker class tests that made success conditional (or downright non deterministic) on hardware it was run on. Centered around this condition:
https://github.com/pcdshub/BEAMS/blob/4be9dc569c857e275fe573ea19e35b926ec358a1/beams/tests/test_worker.py#L28-L29
This was intended to have the logic:
> Keep work thread alive until stop work signal is sent *and* the logical task is completed
The issue being with being with no sleep in the work function on sufficiently fast hardware or with a significantly long wait for whatever reason between these two lines: https://github.com/pcdshub/BEAMS/blob/4be9dc569c857e275fe573ea19e35b926ec358a1/beams/tests/test_worker.py#L32-L33
It could count up very high as seen …
> FIX: race condition in test worker made it conditional on hardware speed

- beams/behavior_tree/ActionNode.py
- beams/behavior_tree/ActionWorker.py
- beams/behavior_tree/CheckAndDo.py
- beams/sequencer/helpers/Worker.py
- beams/tests/artifacts/eggs.json
- beams/tests/artifacts/eggs2.json
- beams/tests/test_check_and_do.py
- beams/tests/test_leaf_node.py
- beams/tests/test_sequencer_state.py
- beams/tests/test_tree_generator.py
- beams/tests/test_worker.py
- beams/tree_config.py
The base `Worker` class was previously implemented to wrap `multiprocessing.Process` such that we could standardize process spawning and management mechanisms and propagate those changes efficiently through the codebase. 
With this in mind it made sense for our ActionNodes which inherently utilize Process's to build off of this functionality. 
We made a subclass of `Worker` called `ActionNodeWorker` which extends the Worker base class to hold the necessary interprocess communication elements needed by any ActionNode in relation to its spawned processes namely:
* __voltaile_status__ : a `multiprocessing.Value` which wraps an enum to communcate BT status up to parent node
* completion_condition: the `Callable[[None], bool]`[^1] which determines work function completion
[^1]: for full …
> ENH: making doing work better

- beams/behavior_tree/ActionNode.py
- beams/behavior_tree/ActionWorker.py
- beams/behavior_tree/ConditionNode.py
- beams/logging.py
- beams/logging.yml
- beams/sequencer/SequenceClient.py
- beams/sequencer/SequenceServer.py
- beams/sequencer/Sequencer.py
- beams/sequencer/SequencerState.py
- beams/sequencer/helpers/PriorityQueue.py
- beams/sequencer/helpers/SharedEnum.py
- beams/sequencer/helpers/Worker.py
- beams/tests/conftest.py
- beams/tests/test_check_and_do.py
- beams/tests/test_leaf_node.py
- beams/tests/test_sequencer_state.py
- beams/tests/test_worker.py
- beams/tree_config.py
- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/41-enh_mp_logging.rst
- requirements.txt
- Adds logging framework to allow workers in multiprocessing.Process to log to a central logger
- Refactors ActionNode work function signatures to expect a `py_trees.common.Status` returned.  This allows us to do common nitty gritty work and not expose that to the user.
- Adjusts tests that are affected by these changes.  Also makes tests more pytest-y 
- Removes ability for `Worker` to "bind" methods to itself (this never worked properly in the first place)
<details><summary>`pytest test_check_and_do.py -s`</summary>
<p>
```bash
(pcds-5.9.0+beams)roberttk@psbuild-rhel7-01:~/devrepos/BEAMS(enh_mp_logging -)$ python -m pytest beams/tests/test_check_and_do.py  -s
============================================================================================ test session starts …
```
> ENH/REF: Enable logging through multiprocessing, refactor node work signatures

- beams/__init__.py
- beams/__main__.py
- beams/bin/__init__.py
- beams/bin/main.py
- beams/bin/run.py
- beams/bin/run_main.py
- beams/logging.py
- beams/logging.yml
- docs/source/upcoming_release_notes/44-enh_cli.rst
- Add a cli framework (that I keep lifting from atef)
- Fix versioning entrypoint (`beams.__version__`)
- Fixes a bit of a logging oversight, don't disable existing loggers when `setup_logging` is called
In partial response to #10 .  When this is in our environment we won't be able to ask users to find the makefile and run commands with it.  This gives us standard python cli entrypoints.  
I could think of a few entrypoints we might add, but didn't want to jump the gun before we discussed them.  
- `beams run`: run a provided tree.  I added this subcommand as an example, but it could use more arguments (tick rate, tick mode {continuous, fixed number, idk}, ...)
- `beams start-server`: start the sequencer server that's currently invoked via `make run_sequencer`
- `beams test_ioc`: start …
> ENH: Add cli framework

- .github/workflows/standard.yml
- docs/source/upcoming_release_notes/51-tst_pip_only.rst
Disable conda tests in a personal fork of pcds-ci-helpers, point BEAMS to that branch
I'm tired of the ❌ 
A couple of options to fix this properly
* Add an option for pip-installs in conda builds (I like this one least, given general guidance to not mix conda/pip)
* add an option to ci-helpers to turn off certain tests (I don't like this)
* upload py-trees to pcds-tag or some other channel ourselves (I like this one the most, but the bar is low)
This PR
This PR
> TST: disable conda tests using personal branch

- beams/bin/gen_test_ioc.py
- beams/bin/gen_test_ioc_main.py
- beams/bin/main.py
- beams/bin/test_ioc.py.j2
- beams/tests/test_bin.py
- docs/source/upcoming_release_notes/57-enh_test_ioc_gen.rst
- requirements.txt
Add a subcommand that takes a tree .json file, scrapes it for "pv" fields, and generates a boilerplate caproto ioc (some configuration required) for use in testing.
Split off from #54 
Future to-do options:
In #54 I had a tree with too many PVs to fill accurately by hand, so I created this helper.
Interactively only
Added a unit test that generates a caproto ioc and imports to check it has the right PV in it.
Later, in pre-release notes
> ENH: add test ioc generator from #54

- beams/tests/test_tree_generator.py
- beams/tree_config.py
- docs/source/upcoming_release_notes/58-enh_add_serialize_helper.rst
Include `save_tree_item_to_path`, a companion to `get_tree_from_path` that takes a fully constructed behavior tree item and saves it to a json file. It is intended that any tree serialized this way will be usable by `get_tree_from_path`.
I had to google `apischema`'s API to serialize my behavior tree and I thought I shouldn't have to do that.
Interactively and added a unit test.
I added a pre-release documentation entry.
> ENH: include save_tree_to_path from #54

- beams/tests/artifacts/egg_generator.py
- docs/source/upcoming_release_notes/65-tst_add_chicken.rst
- Adds a 🐔 so we can make 🥚 whenever our model schema changes
If we're re-doing how tagged unions etcs are defined, we'll need to re-generate the json serialized configs
I ran `python egg_generator.py` once, and confirmed they re-made the configs
This PR
> TST: add egg_generator for re-creating serialized json artifacts

- beams/tests/artifacts/egg_generator.py
- beams/tests/artifacts/eggs.json
- beams/tests/artifacts/eggs2.json
- beams/tests/artifacts/im2l0_test.json
- beams/tests/test_tree_config.py
- beams/tree_config.py
- docs/source/upcoming_release_notes/61-enh_check_and_do_more.rst
- Create a dummy check item called `UseCheckConditionItem`
- When a `CheckAndDoItem` is created with a `do` entry that has no `termination_check`, replace the termination check with `UseCheckConditionItem`
- When a `CheckAndDoItem` is expanded to a tree, re-use the `check` item as the `do`'s `termination_check`.
- I shouldn't need to specify this, it's redundant
- Without this PR, the `CheckAndDoItem` serializes with two copies of the same check item, but with this PR the `termination_check` serializes to a conceptual pointer to the check item instead. This makes it easier to edit the trees in place without having to redo changes in multiple dataclasses.
- Without this PR, the default handling for `termination_check` will always fail (compare blank PV to static number)
Added a unit test …
> ENH: default handling for check_and_do with no termination check

- beams/behavior_tree/ActionNode.py
- beams/behavior_tree/ActionWorker.py
- beams/sequencer/helpers/Timer.py
- beams/tests/test_leaf_node.py
- beams/tests/test_timer.py
Want to allow work function of `ActionNode`'s `ActionWorker` to timeout. 
**Specifically** if the action performed in the work function is ineffectual. I.e. the work done in the work function never satisfies the completion condition. This **does not** guard against the case in which the work function itself hangs. 
This motivated:
- Moving the `wrapped_action_work` to the `ActionWorker`, keeps file sizes and contents reasonable. This did lead to what may be considered a pythonic sin of  a pass-through definition in ActionNode; however for generally cleanliness of code base I would strongly argue this is best. 
- Creating a helper `Timer` class. One can imagine this will be used elsewhere. This can also extend the `time.perf_counter` method to be a code timer across the codebase
We want …
> Adding timeout functionality to action nodes for ineffectual work functions

- beams/behavior_tree/ActionNode.py
- beams/tests/conftest.py
- beams/tests/test_check_and_do.py
- beams/tests/test_leaf_node.py
- beams/tests/test_tree_generator.py
- docs/source/upcoming_release_notes/70-tst_end_spam.rst
- pyproject.toml
- Add `shutdown` method to `ActionNode` to clean up the worker on shutdown. `py_trees` describes this as something like "the opposite of `setup`" so since we set the worker up in `setup`, this seems like the canonical place to clean up the worker. 
- Tweak `ActionNode`'s logic so it only cleans up the worker once.
- Create a helper for the test suite that can be used to register behavior trees and nodes for cleanup at the end of a unit test. This will effectively stop the workers between tests.
- Apply this helper to all the tests that need it.
- Register a dummy "flaky" mark
- Stopping work with the `atexit` hook is correct and necessary, but causes issues (spam) in `pytest` due to some sort of cleanup ordering that I wasn't able to pin down.
- In other cases (qtbot) there is precedence …
> TST: clean up pytest spam, warnings

- beams/behavior_tree/action_node.py
- beams/bin/beams_service.py
- beams/service/helpers/worker.py
- beams/service/rpc_handler.py
- beams/service/tree_ticker.py
The next logical step in this whole dealio - actually loading trees into service memory and ticking them so they do their job.
The big push of this was to do the loading into memory and process management, which python makes not fun to debug. 
1. Main thread spawns a process that handles work for beams_service. 
2. Beams_service process spawns:
a. Process which handles RPC 
b. Manager daemon[^1]
3. As per usual each action node spawns its own persistent process to handle its work[^2]
The trees are stored in a tree dictionary object that is accessed via the Manager for process safety things as in this design two processes will have to be aware of TreeState; the process the responds to HeartBeat messages and the process that handles commands.[^3] 
[^3]: there could've been a world where one …
> Loading trees into memory of BeamsService and ticking those trees

- beams/behavior_tree/action_node.py
- beams/bin/beams_service.py
- beams/service/tree_ticker.py
Implementing tick interactive for our trees that are being managed by BEAMSService. 
Trying to break out of the mongo PR pattern. 
We had continuous ticking down now we have interactive. Yay.
With the testing suite.
All of this raises the good question.... How are we going to represent this to the UI via the client interface.
I can imagine a service endpoint: 
`GetTreeRepresentation(tree_name)`  that returns some serialization of tree state in such a way that can then be rendered by the client.
> feat: got interactive ticking on the service

- beams/tests/artifacts/egg_generator.py
- beams/tests/test_bin.py
- beams/tests/test_serialize.py
- beams/tree_config/base.py
- beams/tree_config/condition.py
- beams/tree_config/value.py
- examples/mfx_dg1/mfx_tree.py
Worked with @tangkong a _while_ ago to add granularity to our values by creating a `BaseValue` class distinct from `BaseItem` 
This was done by moving `FixedValue` and `EPICSValue` out from the `tree_config/base.py` and into the new `tree_config/value.py` and having these items base themselves of the new class `BaseValue`. This also includes a new process safe value type: `ProcessIntValue`
This can be seen largely as a chore commit; however, this important increase in granularity can let us programmatically retrieve values from a more diverse locations in memory / serializable locations.
Yep! 
In this PR.....
> adding abstraction and granularity to the values we seraliaze and compare too

- beams/service/rpc_client.py
- beams/tests/config.cfg
- beams/tests/test_rpc_client.py
- docs/source/upcoming_release_notes/89-enh_config_client.rst
Simple config loading setup for `RPCClient`.  Currently only has server address information, but we could always add more
We wanted some better way of storing and setting `RPCClient` information
Some basic tests have been added
This PR, some docstrings.  The acceptable keys are noted in a docstring, but it should probably live somewhere else long term
> ENH: add ability to load client from config

- beams/service/remote_calls/behavior_tree.proto
- beams/service/tree_ticker.py
- beams/tests/test_rpc_handshakes.py
- docs/source/upcoming_release_notes/99-mnt_paused_heartbeat.rst
Adds a `TreeStatus` enum to be delivered in the `BehaviorTreeUpdateMessage`s, which reports the meta status of the tree as one of:
* IDLE
* RUNNING
* WAITING_ACK
* ERROR
This is distinct from the tick status, as any one of these tree statuses can be combined with any tick status (an IDLE tree can have a root node that reports success/failure/running, as can a RUNNING tree etc)
I want to be able to represent this information in GUI applications.  Closes #95 
More directly, once you pause a tree, there's no way to find out what trees are paused or running based on the heartbeat message.  
Tests have been added, and existing tests have been augmented.
This PR
> MNT: augment protos to report Tree status

- beams/bin/main.py
- beams/bin/ui.py
- beams/bin/ui_main.py
- beams/tests/test_bin.py
- beams/tree_config/action.py
- beams/tree_config/composite.py
- beams/tree_config/condition.py
- beams/tree_config/idiom.py
- beams/tree_config/prebuilt/__init__.py
- beams/tree_config/py_trees.py
- beams/widgets/action.py
- beams/widgets/base.py
- beams/widgets/models.py
- docs/source/upcoming_release_notes/100-enh_basic_nodes.rst
- requirements.txt
- Adds basic framework for setting up a node editor that features BEAMS node types
- Sets up systems for automatically creating node classes for each behavior tree node (BaseItem)
- Sets up a system for creating and collecting embedded widgets for these modes
- Adds pcdshub/qtpynodeeditor as a dependency
TODO:
We dream of being able to create a tree in the BEAMS gui, and this is our first steps toward this
Much of the ui finessing should probably be done in the qtpynodeeditor side.  I'm working on that in parallel
Lacking a better system, we do a bit of pattern matching between the tree_config submodule.  We gather all the `_supported_items` from the various submodules, and create a NodeDataModel using the appropriate mixin classes.
We do similar pattern matching on the embedded widget …
> ENH: basic node editor functionality

- beams/service/rpc_client.py
- docs/source/upcoming_release_notes/106-fix_disable_http_proxy.rst
HTTP proxy setting send beams commands to psproxy instead of to the desired server. This PR disables HTTP proxies for the BEAMS client.
The http proxies set here
https://github.com/pcdshub/shared-dotfiles/blob/2f38a40712bdade5ffd9892a89b4c2451625cc67/on_site/bashrc#L214-L215
break beams
Interactively by making sure we can use the beams client using a prod bashrc
Here only and in pre-release notes
> FIX: disable ecs shared dotfiles http config that breaks beams

- beams/service/rpc_client.py
- docs/source/upcoming_release_notes/107-client-cli-fix.rst
Very small client CLI bug that snuck in. 
Old bug reproduced through spawning a tree and trying to start it.
> FIX: small syntax fix in getting correct client method from cli

- beams/bin/service_main.py
- beams/service/remote_calls/beams_rpc.proto
- beams/service/remote_calls/behavior_tree.proto
- beams/service/remote_calls/command.proto
- beams/service/remote_calls/heartbeat.proto
- beams/service/rpc_client.py
- beams/service/rpc_handler.py
- beams/service/tree_ticker.py
- beams/tests/test_rpc_handshakes.py
- beams/tests/test_service_proto_messages.py
- beams/tests/test_treeidkey.py
- docs/source/upcoming_release_notes/109-enh_detailed_proto.rst
- Adds the ability for the BEAMS service to provide detailed messages to a client, including the name, uuid, and status of every node in a tree
- Adds `TreeDetails` proto message, which holds `NodeInfo`
- Adds `NodeInfo`, a recursive message that details the node id, its status, and its childrens' `NodeInfo`
- Adds code paths for the service to create and return these `TreeDetails` objects
- Adjusts the `RPCHandler` and `TreeTicker` to use UUIDs as the primary method of identifying trees
- the "tree_dict" passed around is now keyed by a `TreeIdKey` object, which handles equality checks between both strings and uuids (in addition to its own type) 
- Ensures that the "name" used to identify the tree is the one the client provides, not the name specified in a tree config file
- multiple …
> ENH: add detailed `TreeDetails` proto, identify trees and nodes by uuid

- beams/service/remote_calls/behavior_tree.proto
- beams/service/rpc_client.py
- beams/service/tree_ticker.py
- beams/tests/test_qt_models.py
- beams/widgets/qt_models.py
- docs/source/upcoming_release_notes/114-enh_type_detailed_proto.rst
- Adds `type` to the `TreeDetails` proto
- Adds checks in the `QtBTreeItem` update methods that reference this information
- Adds constructor methods to create a `QtBTreeItem` entirely from a `TreeDetails` message
- for use in displaying tree information from the service
Ew it's all string comparison.  Surely this doesn't bite us later.
Some tests have been added and modified
This PR, and some docstrings
> ENH: Augment detailed tree proto to include node type
